### ISSUE TITLE
GPU memory for training segmentation head

### ISSUE THREAD

**Issue by Raspberry-beans** [MohammedSB/DINOv2ForMedical#1]
Hi, Thanks for the great work.

I will be training a segmentation head (starting from simplest linear head) on top of frozen DINOv2 backbone on my few shot custom medical images. My available GPU memory is only 8GB.

Would this memory space be enough for training a simple prediction head?

Your guidance is appreciated.
Thanks in advance!

**Comment by MohammedSB** [comment]
Hi, thank you for your interest in our work!

I think 8GB should fit if you freeze the DINOv2 backbone, especially if you use a linear decoder. Try the ViT-L model first, if you get an error, try the base version. You can experiment with different batch sizes as well to make sure that there is enough GPU memory to do inference.

Let me know if you need additional help.

**Comment by Raspberry-beans** [comment]
Thanks a lot for your reply. I will start with ViT_L and fine tune linear head first.

Also there are other parameter-efficient fine tuning techniques for vision foundation models like SAM, DINOv2.

As in the paper, it is mentioned that you adopted LoRA fine-tuning as well. **Table 7** shows the number of trainable parameters in case of LoRA. Although being less than 1%, the number of trainable params are still in millions. Does this mean, even in case of efficient fine tuning approaches, we need sufficient memory requirements?

![Screenshot 2024-01-11 234343](https://github.com/MohammedSB/DINOv2ForRadiology/assets/69916197/87d40dba-16ae-42c1-8b87-a21568fb2062)

Thanks again!

**Comment by MohammedSB** [comment]
The values for this table are for the ViT-g, the ViT-L should have around 4 times less parameters. That will be around ~2M for LoRA. Also, you can try changing the LoRA rank **r** parameter, which will change the number of parameters. In our study we used r=48, but we observed a similar performance with r=32.

Keep in mind that the best way to know if something will fit in your GPU is to try it. Also keep in mind that our code does not implement LoRA for segmentation, since we didn't cover that in our study, but should it be simple to implement.

**Comment by Raspberry-beans** [comment]
Thanks for clarifying!
